const ownerRule = '@request.auth.id != "" && user_id = @request.auth.id'

const textField = (name, extra = {}) => ({
  name,
  type: 'text',
  required: false,
  ...extra,
})

const numberField = (name, extra = {}) => ({
  name,
  type: 'number',
  required: false,
  ...extra,
})

const boolField = (name, extra = {}) => ({
  name,
  type: 'bool',
  required: false,
  ...extra,
})

const baseCollection = (name, fields) => ({
  name,
  type: 'base',
  listRule: ownerRule,
  viewRule: ownerRule,
  createRule: ownerRule,
  updateRule: ownerRule,
  deleteRule: ownerRule,
  fields,
})

export const collections = [
  {
    name: 'users',
    type: 'auth',
    listRule: null,
    viewRule: 'id = @request.auth.id',
    createRule: '',
    updateRule: 'id = @request.auth.id',
    deleteRule: 'id = @request.auth.id',
    manageRule: 'id = @request.auth.id',
    fields: [],
    passwordAuth: {
      enabled: true,
      identityFields: ['email'],
    },
    verificationTemplate: {},
    resetPasswordTemplate: {},
    confirmEmailChangeTemplate: {},
  },
  baseCollection('exercises', [
    textField('app_id', { required: true }),
    textField('user_id', { required: true }),
    textField('movement_name', { required: true }),
    textField('body_region'),
    textField('muscle_group'),
    textField('equipment'),
    textField('preferred_weight_unit'),
    textField('tracking_mode', { required: true }),
    numberField('default_rest_seconds', { onlyInt: true }),
    boolField('is_custom', { required: true }),
    textField('deleted_at'),
    textField('created_at', { required: true }),
    textField('updated_at', { required: true }),
  ]),
  baseCollection('workout_templates', [
    textField('app_id', { required: true }),
    textField('user_id', { required: true }),
    textField('name', { required: true }),
    textField('notes'),
    textField('deleted_at'),
    textField('created_at', { required: true }),
    textField('updated_at', { required: true }),
  ]),
  baseCollection('template_exercises', [
    textField('app_id', { required: true }),
    textField('user_id', { required: true }),
    textField('template_id', { required: true }),
    textField('exercise_id', { required: true }),
    numberField('sort_order', { onlyInt: true, required: true }),
    textField('deleted_at'),
    textField('created_at', { required: true }),
    textField('updated_at', { required: true }),
  ]),
  baseCollection('template_sets', [
    textField('app_id', { required: true }),
    textField('user_id', { required: true }),
    textField('template_exercise_id', { required: true }),
    numberField('sort_order', { onlyInt: true, required: true }),
    textField('set_kind', { required: true }),
    numberField('target_reps', { onlyInt: true }),
    numberField('target_weight'),
    numberField('target_assistance_weight'),
    numberField('target_duration_seconds', { onlyInt: true }),
    textField('deleted_at'),
    textField('created_at', { required: true }),
    textField('updated_at', { required: true }),
  ]),
  baseCollection('workouts', [
    textField('app_id', { required: true }),
    textField('user_id', { required: true }),
    textField('template_id'),
    textField('name', { required: true }),
    textField('notes'),
    numberField('calories_burned'),
    textField('status', { required: true }),
    textField('started_at', { required: true }),
    textField('ended_at'),
    textField('deleted_at'),
    textField('created_at', { required: true }),
    textField('updated_at', { required: true }),
  ]),
  baseCollection('workout_exercises', [
    textField('app_id', { required: true }),
    textField('user_id', { required: true }),
    textField('workout_id', { required: true }),
    textField('exercise_id', { required: true }),
    textField('notes'),
    numberField('sort_order', { onlyInt: true, required: true }),
    textField('deleted_at'),
    textField('created_at', { required: true }),
    textField('updated_at', { required: true }),
  ]),
  baseCollection('logged_sets', [
    textField('app_id', { required: true }),
    textField('user_id', { required: true }),
    textField('workout_exercise_id', { required: true }),
    textField('planned_set_id'),
    numberField('sort_order', { onlyInt: true, required: true }),
    textField('set_kind', { required: true }),
    numberField('reps', { onlyInt: true }),
    numberField('weight'),
    numberField('assistance_weight'),
    numberField('duration_seconds', { onlyInt: true }),
    textField('completed_at'),
    textField('deleted_at'),
    textField('created_at', { required: true }),
    textField('updated_at', { required: true }),
  ]),
  baseCollection('preferences', [
    textField('app_id', { required: true }),
    textField('user_id', { required: true }),
    textField('weight_unit', { required: true }),
    numberField('default_rest_seconds', { onlyInt: true, required: true }),
    textField('updated_at', { required: true }),
  ]),
]
