import type { Exercise } from '../lib/types'
import { nowIso } from '../lib/time'

const defaults = [
  ['Bench Press', 'Chest', 'Mid Chest', 'Barbell', 'weight_reps', 150],
  ['Bench Press', 'Chest', 'Mid Chest', 'Dumbbell', 'weight_reps', 120],
  ['Bench Press', 'Chest', 'Upper Chest', 'Barbell', 'weight_reps', 150],
  ['Bench Press', 'Chest', 'Upper Chest', 'Dumbbell', 'weight_reps', 120],
  ['Bench Press', 'Chest', 'Lower Chest', 'Barbell', 'weight_reps', 150],
  ['Squat', 'Legs', 'Quads', 'Barbell', 'weight_reps', 180],
  ['Front Squat', 'Legs', 'Quads', 'Barbell', 'weight_reps', 180],
  ['Bulgarian Split Squat', 'Legs', 'Quads', 'Dumbbell', 'weight_reps', 120],
  ['Leg Press', 'Legs', 'Quads', 'Machine', 'weight_reps', 120],
  ['Deadlift', 'Back', 'Spinal Erectors', 'Barbell', 'weight_reps', 210],
  ['Deadlift', 'Legs', 'Glutes', 'Barbell Sumo', 'weight_reps', 210],
  ['Overhead Press', 'Shoulders', 'Front Delts', 'Barbell', 'weight_reps', 150],
  ['Shoulder Press', 'Shoulders', 'Front Delts', 'Dumbbell', 'weight_reps', 120],
  ['Arnold Press', 'Shoulders', 'Front Delts', 'Dumbbell', 'weight_reps', 120],
  ['Row', 'Back', 'Upper Back', 'Barbell', 'weight_reps', 150],
  ['Row', 'Back', 'Upper Back', 'Pendlay Barbell', 'weight_reps', 150],
  ['Row', 'Back', 'Upper Back', 'T-Bar', 'weight_reps', 120],
  ['Row', 'Back', 'Lats', 'Single-Arm Dumbbell', 'weight_reps', 120],
  ['Lat Pulldown', 'Back', 'Lats', 'Cable', 'weight_reps', 120],
  ['Seated Row', 'Back', 'Upper Back', 'Cable', 'weight_reps', 120],
  ['Pull-Up', 'Back', 'Lats', 'Bodyweight', 'bodyweight_reps', 120],
  ['Chin-Up', 'Arms', 'Biceps', 'Bodyweight', 'bodyweight_reps', 120],
  ['Pull-Up', 'Back', 'Lats', 'Neutral Grip', 'bodyweight_reps', 120],
  ['Push-Up', 'Chest', 'Mid Chest', 'Bodyweight', 'bodyweight_reps', 90],
  ['Push-Up', 'Arms', 'Triceps', 'Diamond', 'bodyweight_reps', 90],
  ['Dip', 'Chest', 'Lower Chest', 'Bodyweight', 'bodyweight_reps', 120],
  ['Push-Up', 'Shoulders', 'Front Delts', 'Pike', 'bodyweight_reps', 90],
  ['Pull-Up', 'Back', 'Lats', 'Band', 'assisted_bodyweight_reps', 120],
  ['Pull-Up', 'Back', 'Lats', 'Machine Assist', 'assisted_bodyweight_reps', 120],
  ['Dip', 'Arms', 'Triceps', 'Machine Assist', 'assisted_bodyweight_reps', 120],
  ['Fly', 'Chest', 'Mid Chest', 'Cable', 'weight_reps', 90],
  ['Fly', 'Chest', 'Mid Chest', 'Pec Deck', 'weight_reps', 90],
  ['Romanian Deadlift', 'Legs', 'Hamstrings', 'Barbell', 'weight_reps', 150],
  ['Romanian Deadlift', 'Legs', 'Hamstrings', 'Dumbbell', 'weight_reps', 120],
  ['Good Morning', 'Legs', 'Hamstrings', 'Barbell', 'weight_reps', 150],
  ['Hip Thrust', 'Legs', 'Glutes', 'Barbell', 'weight_reps', 120],
  ['Glute Bridge', 'Legs', 'Glutes', 'Barbell', 'weight_reps', 120],
  ['Walking Lunge', 'Legs', 'Glutes', 'Dumbbell', 'weight_reps', 120],
  ['Leg Curl', 'Legs', 'Hamstrings', 'Machine', 'weight_reps', 90],
  ['Leg Extension', 'Legs', 'Quads', 'Machine', 'weight_reps', 90],
  ['Calf Raise', 'Legs', 'Calves', 'Standing Machine', 'weight_reps', 75],
  ['Calf Raise', 'Legs', 'Calves', 'Seated Machine', 'weight_reps', 75],
  ['Lateral Raise', 'Shoulders', 'Side Delts', 'Dumbbell', 'weight_reps', 75],
  ['Rear Delt Fly', 'Shoulders', 'Rear Delts', 'Dumbbell', 'weight_reps', 75],
  ['Face Pull', 'Shoulders', 'Rear Delts', 'Cable', 'weight_reps', 75],
  ['Upright Row', 'Shoulders', 'Side Delts', 'Barbell', 'weight_reps', 90],
  ['Curl', 'Arms', 'Biceps', 'Barbell', 'weight_reps', 75],
  ['Curl', 'Arms', 'Biceps', 'Dumbbell', 'weight_reps', 75],
  ['Curl', 'Arms', 'Biceps', 'Hammer Dumbbell', 'weight_reps', 75],
  ['Curl', 'Arms', 'Biceps', 'Preacher Machine', 'weight_reps', 75],
  ['Triceps Pushdown', 'Arms', 'Triceps', 'Cable', 'weight_reps', 75],
  ['Triceps Extension', 'Arms', 'Triceps', 'Overhead Cable', 'weight_reps', 75],
  ['Skullcrusher', 'Arms', 'Triceps', 'Barbell', 'weight_reps', 75],
  ['Bench Press', 'Arms', 'Triceps', 'Close Grip Barbell', 'weight_reps', 120],
  ['Wrist Curl', 'Arms', 'Forearms', 'Barbell', 'weight_reps', 60],
  ['Leg Raise', 'Core', 'Abs', 'Hanging', 'bodyweight_reps', 60],
  ['Crunch', 'Core', 'Abs', 'Bodyweight', 'bodyweight_reps', 45],
  ['Sit-Up', 'Core', 'Abs', 'Bodyweight', 'bodyweight_reps', 45],
  ['Russian Twist', 'Core', 'Obliques', 'Bodyweight', 'bodyweight_reps', 45],
  ['Back Extension', 'Core', 'Lower Back', 'Bodyweight', 'bodyweight_reps', 60],
  ['Crunch', 'Core', 'Abs', 'Cable', 'weight_reps', 60],
  ['Ride', 'Cardio', 'Cycling', 'Stationary Bike', 'duration', 30],
  ['Walk', 'Cardio', 'Walking', 'Outdoor', 'duration', 30],
  ['Run', 'Cardio', 'Running', 'Treadmill', 'duration', 30],
  ['Run', 'Cardio', 'Running', 'Outdoor', 'duration', 30],
  ['Row', 'Cardio', 'Rowing', 'Erg', 'duration', 45],
  ['Elliptical', 'Cardio', 'Conditioning', 'Machine', 'duration', 30],
] as const

export function createSeedExercises() {
  const timestamp = nowIso()

  return defaults.map<Exercise>(([movementName, bodyRegion, muscleGroup, equipment, trackingMode, rest]) => ({
    id: `exercise_seed_${`${movementName}_${equipment}`.toLowerCase().replaceAll(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '')}`,
    movementName,
    bodyRegion,
    muscleGroup,
    equipment,
    preferredWeightUnit: null,
    trackingMode,
    defaultRestSeconds: rest,
    isCustom: false,
    deletedAt: null,
    createdAt: timestamp,
    updatedAt: timestamp,
    syncStatus: 'synced',
  }))
}
