import type { Exercise } from '../lib/types'
import { nowIso } from '../lib/time'

const defaults = [
  ['Bench Press', 'Chest', 'Mid Chest', 'Barbell', 'weight_reps', 150],
  ['Incline Bench Press', 'Chest', 'Upper Chest', 'Barbell', 'weight_reps', 150],
  ['Decline Bench Press', 'Chest', 'Lower Chest', 'Barbell', 'weight_reps', 150],
  ['Dumbbell Bench Press', 'Chest', 'Mid Chest', 'Dumbbell', 'weight_reps', 120],
  ['Squat', 'Legs', 'Quads', 'Barbell', 'weight_reps', 180],
  ['Front Squat', 'Legs', 'Quads', 'Barbell', 'weight_reps', 180],
  ['Bulgarian Split Squat', 'Legs', 'Quads', 'Dumbbell', 'weight_reps', 120],
  ['Leg Press', 'Legs', 'Quads', 'Machine', 'weight_reps', 120],
  ['Deadlift', 'Back', 'Spinal Erectors', 'Barbell', 'weight_reps', 210],
  ['Sumo Deadlift', 'Legs', 'Glutes', 'Barbell', 'weight_reps', 210],
  ['Overhead Press', 'Shoulders', 'Front Delts', 'Barbell', 'weight_reps', 150],
  ['Seated Dumbbell Shoulder Press', 'Shoulders', 'Front Delts', 'Dumbbell', 'weight_reps', 120],
  ['Arnold Press', 'Shoulders', 'Front Delts', 'Dumbbell', 'weight_reps', 120],
  ['Barbell Row', 'Back', 'Upper Back', 'Barbell', 'weight_reps', 150],
  ['Pendlay Row', 'Back', 'Upper Back', 'Barbell', 'weight_reps', 150],
  ['T-Bar Row', 'Back', 'Upper Back', 'Machine', 'weight_reps', 120],
  ['Single-Arm Dumbbell Row', 'Back', 'Lats', 'Dumbbell', 'weight_reps', 120],
  ['Lat Pulldown', 'Back', 'Lats', 'Cable', 'weight_reps', 120],
  ['Seated Cable Row', 'Back', 'Upper Back', 'Cable', 'weight_reps', 120],
  ['Pull-Up', 'Back', 'Lats', 'Bodyweight', 'bodyweight_reps', 120],
  ['Chin-Up', 'Arms', 'Biceps', 'Bodyweight', 'bodyweight_reps', 120],
  ['Neutral-Grip Pull-Up', 'Back', 'Lats', 'Bodyweight', 'bodyweight_reps', 120],
  ['Push-Up', 'Chest', 'Mid Chest', 'Bodyweight', 'bodyweight_reps', 90],
  ['Diamond Push-Up', 'Arms', 'Triceps', 'Bodyweight', 'bodyweight_reps', 90],
  ['Dip', 'Chest', 'Lower Chest', 'Bodyweight', 'bodyweight_reps', 120],
  ['Pike Push-Up', 'Shoulders', 'Front Delts', 'Bodyweight', 'bodyweight_reps', 90],
  ['Banded Pull-Up', 'Back', 'Lats', 'Band', 'assisted_bodyweight_reps', 120],
  ['Assisted Pull-Up', 'Back', 'Lats', 'Machine', 'assisted_bodyweight_reps', 120],
  ['Assisted Dip', 'Arms', 'Triceps', 'Machine', 'assisted_bodyweight_reps', 120],
  ['Incline Dumbbell Press', 'Chest', 'Upper Chest', 'Dumbbell', 'weight_reps', 120],
  ['Cable Fly', 'Chest', 'Mid Chest', 'Cable', 'weight_reps', 90],
  ['Pec Deck', 'Chest', 'Mid Chest', 'Machine', 'weight_reps', 90],
  ['Romanian Deadlift', 'Legs', 'Hamstrings', 'Barbell', 'weight_reps', 150],
  ['Good Morning', 'Legs', 'Hamstrings', 'Barbell', 'weight_reps', 150],
  ['Hip Thrust', 'Legs', 'Glutes', 'Barbell', 'weight_reps', 120],
  ['Glute Bridge', 'Legs', 'Glutes', 'Barbell', 'weight_reps', 120],
  ['Walking Lunge', 'Legs', 'Glutes', 'Dumbbell', 'weight_reps', 120],
  ['Leg Curl', 'Legs', 'Hamstrings', 'Machine', 'weight_reps', 90],
  ['Leg Extension', 'Legs', 'Quads', 'Machine', 'weight_reps', 90],
  ['Standing Calf Raise', 'Legs', 'Calves', 'Machine', 'weight_reps', 75],
  ['Seated Calf Raise', 'Legs', 'Calves', 'Machine', 'weight_reps', 75],
  ['Lateral Raise', 'Shoulders', 'Side Delts', 'Dumbbell', 'weight_reps', 75],
  ['Rear Delt Fly', 'Shoulders', 'Rear Delts', 'Dumbbell', 'weight_reps', 75],
  ['Face Pull', 'Shoulders', 'Rear Delts', 'Cable', 'weight_reps', 75],
  ['Upright Row', 'Shoulders', 'Side Delts', 'Barbell', 'weight_reps', 90],
  ['Barbell Curl', 'Arms', 'Biceps', 'Barbell', 'weight_reps', 75],
  ['Dumbbell Curl', 'Arms', 'Biceps', 'Dumbbell', 'weight_reps', 75],
  ['Hammer Curl', 'Arms', 'Biceps', 'Dumbbell', 'weight_reps', 75],
  ['Preacher Curl', 'Arms', 'Biceps', 'Machine', 'weight_reps', 75],
  ['Triceps Pushdown', 'Arms', 'Triceps', 'Cable', 'weight_reps', 75],
  ['Overhead Triceps Extension', 'Arms', 'Triceps', 'Cable', 'weight_reps', 75],
  ['Skullcrusher', 'Arms', 'Triceps', 'Barbell', 'weight_reps', 75],
  ['Close-Grip Bench Press', 'Arms', 'Triceps', 'Barbell', 'weight_reps', 120],
  ['Wrist Curl', 'Arms', 'Forearms', 'Barbell', 'weight_reps', 60],
  ['Hanging Leg Raise', 'Core', 'Abs', 'Bodyweight', 'bodyweight_reps', 60],
  ['Crunch', 'Core', 'Abs', 'Bodyweight', 'bodyweight_reps', 45],
  ['Sit-Up', 'Core', 'Abs', 'Bodyweight', 'bodyweight_reps', 45],
  ['Russian Twist', 'Core', 'Obliques', 'Bodyweight', 'bodyweight_reps', 45],
  ['Back Extension', 'Core', 'Lower Back', 'Bodyweight', 'bodyweight_reps', 60],
  ['Cable Crunch', 'Core', 'Abs', 'Cable', 'weight_reps', 60],
] as const

export function createSeedExercises() {
  const timestamp = nowIso()

  return defaults.map<Exercise>(([name, bodyRegion, muscleGroup, equipment, trackingMode, rest]) => ({
    id: `exercise_seed_${name.toLowerCase().replaceAll(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '')}`,
    name,
    bodyRegion,
    muscleGroup,
    equipment,
    trackingMode,
    defaultRestSeconds: rest,
    isCustom: false,
    deletedAt: null,
    createdAt: timestamp,
    updatedAt: timestamp,
    syncStatus: 'synced',
  }))
}
